from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict, List, Optional


PREDEFINED_BASELINES: Dict[str, Dict[str, Any]] = {
    "products": {
        "baseline_key": "products",
        "dataset_name": "product_catalog",
        "baseline_version": "v1",
        "description": "Approved semantic baseline for the products table defined in data architecture.",
        "source_table": "final_products.csv",
        "columns": {
            "product_id": {
                "business_meaning": "Unique identifier for a product listing",
                "role": "identifier",
                "domain": "Commerce",
                "unit": "id",
                "scale": "integer",
                "data_type": "integer",
                "value_direction": "neutral reference key",
            },
            "shop_id": {
                "business_meaning": "Identifier of the shop that owns the product listing",
                "role": "identifier",
                "domain": "Commerce",
                "unit": "id",
                "scale": "integer",
                "data_type": "integer",
                "value_direction": "neutral reference key",
            },
            "name": {
                "business_meaning": "Customer-facing product name",
                "role": "text_attribute",
                "domain": "Commerce",
                "unit": "text",
                "scale": "free_text",
                "data_type": "string",
                "value_direction": "neutral description",
            },
            "category": {
                "business_meaning": "Merchandise category assigned to the product",
                "role": "dimension",
                "domain": "Commerce",
                "unit": "category",
                "scale": "nominal",
                "data_type": "string",
                "value_direction": "neutral grouping",
            },
            "color": {
                "business_meaning": "Primary product color descriptor",
                "role": "dimension",
                "domain": "Commerce",
                "unit": "color",
                "scale": "nominal",
                "data_type": "string",
                "value_direction": "neutral attribute",
            },
            "fabric": {
                "business_meaning": "Main material or fabric used in the product",
                "role": "dimension",
                "domain": "Commerce",
                "unit": "material",
                "scale": "nominal",
                "data_type": "string",
                "value_direction": "neutral attribute",
            },
            "size_range": {
                "business_meaning": "Size range supported by the product listing",
                "role": "dimension",
                "domain": "Commerce",
                "unit": "size",
                "scale": "ordinal",
                "data_type": "string",
                "value_direction": "neutral attribute",
            },
            "price_LKR": {
                "business_meaning": "Displayed selling price of the product in Sri Lankan Rupees",
                "role": "measure",
                "domain": "Commerce",
                "unit": "LKR",
                "scale": "currency",
                "data_type": "decimal",
                "value_direction": "higher means higher selling price",
            },
            "style_tags": {
                "business_meaning": "Tag bundle describing product style, fit, and audience cues",
                "role": "text_attribute",
                "domain": "Commerce",
                "unit": "tags",
                "scale": "multi_label_text",
                "data_type": "string",
                "value_direction": "neutral descriptive tags",
            },
            "product_url": {
                "business_meaning": "Canonical product page URL",
                "role": "identifier",
                "domain": "Commerce",
                "unit": "url",
                "scale": "reference",
                "data_type": "string",
                "value_direction": "neutral reference link",
            },
            "created_ts": {
                "business_meaning": "Original source time fragment captured when the product record was created",
                "role": "timestamp",
                "domain": "Commerce",
                "unit": "time",
                "scale": "time_string",
                "data_type": "string",
                "value_direction": "later means more recent source capture",
            },
            "popularity_score": {
                "business_meaning": "Popularity score assigned to the product listing",
                "role": "score",
                "domain": "Commerce",
                "unit": "score",
                "scale": "normalized_score",
                "data_type": "decimal",
                "value_direction": "higher means more popular",
            },
            "stock_count": {
                "business_meaning": "Available stock quantity for the product listing",
                "role": "measure",
                "domain": "Inventory",
                "unit": "count",
                "scale": "integer",
                "data_type": "integer",
                "value_direction": "higher means more items in stock",
            },
            "created_timestamp": {
                "business_meaning": "Full timestamp when the product record was created",
                "role": "timestamp",
                "domain": "Commerce",
                "unit": "datetime",
                "scale": "timestamp",
                "data_type": "datetime",
                "value_direction": "later means more recent record creation",
            },
        },
    },
    "users": {
        "baseline_key": "users",
        "dataset_name": "user_profiles",
        "baseline_version": "v1",
        "description": "Approved semantic baseline for the users table defined in data architecture.",
        "source_table": "users_dataset.csv",
        "columns": {
            "user_id": {
                "business_meaning": "Unique identifier for a customer account",
                "role": "identifier",
                "domain": "Customer",
                "unit": "id",
                "scale": "integer",
                "data_type": "integer",
                "value_direction": "neutral reference key",
            },
            "name": {
                "business_meaning": "Customer full name",
                "role": "text_attribute",
                "domain": "Customer",
                "unit": "text",
                "scale": "free_text",
                "data_type": "string",
                "value_direction": "neutral profile text",
            },
            "email": {
                "business_meaning": "Customer email address used for communication and login",
                "role": "identifier",
                "domain": "Customer",
                "unit": "email",
                "scale": "reference",
                "data_type": "string",
                "value_direction": "neutral contact identifier",
            },
            "phone": {
                "business_meaning": "Customer phone number for delivery or support contact",
                "role": "identifier",
                "domain": "Customer",
                "unit": "phone",
                "scale": "reference",
                "data_type": "string",
                "value_direction": "neutral contact identifier",
            },
            "shipping_address": {
                "business_meaning": "Primary shipping address for the customer",
                "role": "text_attribute",
                "domain": "Customer",
                "unit": "address",
                "scale": "free_text",
                "data_type": "string",
                "value_direction": "neutral address detail",
            },
            "signup_ts": {
                "business_meaning": "Date when the customer account was created",
                "role": "timestamp",
                "domain": "Customer",
                "unit": "date",
                "scale": "date",
                "data_type": "date",
                "value_direction": "later means more recently signed up",
            },
            "is_active": {
                "business_meaning": "Whether the customer account is currently active",
                "role": "binary_label",
                "domain": "Customer",
                "unit": "boolean",
                "scale": "binary",
                "data_type": "boolean",
                "value_direction": "true means active account",
            },
        },
    },
    "transactions": {
        "baseline_key": "transactions",
        "dataset_name": "sales_transactions",
        "baseline_version": "v1",
        "description": "Approved semantic baseline for the transactions table defined in data architecture.",
        "source_table": "transactions_dataset.csv",
        "columns": {
            "transaction_id": {
                "business_meaning": "Unique identifier for a transaction",
                "role": "identifier",
                "domain": "Sales",
                "unit": "id",
                "scale": "integer",
                "data_type": "integer",
                "value_direction": "neutral reference key",
            },
            "user_id": {
                "business_meaning": "Identifier of the customer who placed the order",
                "role": "identifier",
                "domain": "Sales",
                "unit": "id",
                "scale": "integer",
                "data_type": "integer",
                "value_direction": "neutral reference key",
            },
            "product_id": {
                "business_meaning": "Identifier of the product sold in the transaction",
                "role": "identifier",
                "domain": "Sales",
                "unit": "id",
                "scale": "integer",
                "data_type": "integer",
                "value_direction": "neutral reference key",
            },
            "shop_id": {
                "business_meaning": "Identifier of the shop fulfilling the order",
                "role": "identifier",
                "domain": "Sales",
                "unit": "id",
                "scale": "integer",
                "data_type": "integer",
                "value_direction": "neutral reference key",
            },
            "quantity": {
                "business_meaning": "Number of product units sold in the transaction",
                "role": "measure",
                "domain": "Sales",
                "unit": "count",
                "scale": "integer",
                "data_type": "integer",
                "value_direction": "higher means more items sold",
            },
            "unit_price": {
                "business_meaning": "Selling price per unit before taxes and discounts",
                "role": "measure",
                "domain": "Sales",
                "unit": "LKR",
                "scale": "currency",
                "data_type": "decimal",
                "value_direction": "higher means higher per-item selling price",
            },
            "total_amount": {
                "business_meaning": "Gross transaction amount before discounts and taxes",
                "role": "measure",
                "domain": "Sales",
                "unit": "LKR",
                "scale": "currency",
                "data_type": "decimal",
                "value_direction": "higher means more gross revenue",
            },
            "discount_percent": {
                "business_meaning": "Discount percentage applied to the transaction",
                "role": "measure",
                "domain": "Sales",
                "unit": "percent",
                "scale": "percentage",
                "data_type": "decimal",
                "value_direction": "higher means larger discount share",
            },
            "discount_amount": {
                "business_meaning": "Discount amount deducted from the gross transaction total",
                "role": "measure",
                "domain": "Sales",
                "unit": "LKR",
                "scale": "currency",
                "data_type": "decimal",
                "value_direction": "higher means larger discount value",
            },
            "tax_percent": {
                "business_meaning": "Tax percentage applied to the transaction",
                "role": "measure",
                "domain": "Sales",
                "unit": "percent",
                "scale": "percentage",
                "data_type": "decimal",
                "value_direction": "higher means larger tax share",
            },
            "tax_amount": {
                "business_meaning": "Tax amount added to the transaction",
                "role": "measure",
                "domain": "Sales",
                "unit": "LKR",
                "scale": "currency",
                "data_type": "decimal",
                "value_direction": "higher means larger tax value",
            },
            "final_amount": {
                "business_meaning": "Final sales revenue after applying discounts and taxes",
                "role": "measure",
                "domain": "Sales",
                "unit": "LKR",
                "scale": "currency",
                "data_type": "decimal",
                "value_direction": "higher means more final revenue",
            },
            "payment_method": {
                "business_meaning": "Payment method selected by the customer",
                "role": "dimension",
                "domain": "Sales",
                "unit": "method",
                "scale": "nominal",
                "data_type": "string",
                "value_direction": "neutral payment category",
            },
            "transaction_status": {
                "business_meaning": "Operational status of the transaction lifecycle",
                "role": "dimension",
                "domain": "Sales",
                "unit": "status",
                "scale": "ordinal",
                "data_type": "string",
                "value_direction": "later statuses mean more progressed fulfillment",
            },
            "transaction_date": {
                "business_meaning": "Calendar date when the transaction was recorded",
                "role": "timestamp",
                "domain": "Sales",
                "unit": "date",
                "scale": "date",
                "data_type": "date",
                "value_direction": "later means more recent sale date",
            },
            "transaction_ts": {
                "business_meaning": "Exact timestamp when the transaction was created",
                "role": "timestamp",
                "domain": "Sales",
                "unit": "datetime",
                "scale": "timestamp",
                "data_type": "datetime",
                "value_direction": "later means more recent transaction event",
            },
            "delivery_date": {
                "business_meaning": "Expected or actual delivery date for the order",
                "role": "timestamp",
                "domain": "Sales",
                "unit": "datetime",
                "scale": "timestamp",
                "data_type": "datetime",
                "value_direction": "later means later delivery timing",
            },
            "delivery_address": {
                "business_meaning": "Delivery destination for the order",
                "role": "text_attribute",
                "domain": "Sales",
                "unit": "address",
                "scale": "free_text",
                "data_type": "string",
                "value_direction": "neutral delivery detail",
            },
            "notes": {
                "business_meaning": "Free-text note describing the order context",
                "role": "text_attribute",
                "domain": "Sales",
                "unit": "text",
                "scale": "free_text",
                "data_type": "string",
                "value_direction": "neutral supporting detail",
            },
        },
    },
    "shops": {
        "baseline_key": "shops",
        "dataset_name": "shop_directory",
        "baseline_version": "v1",
        "description": "Approved semantic baseline for the shops table defined in data architecture.",
        "source_table": "shops_dataset.csv",
        "columns": {
            "shop_id": {
                "business_meaning": "Unique identifier for a shop",
                "role": "identifier",
                "domain": "Retail",
                "unit": "id",
                "scale": "integer",
                "data_type": "integer",
                "value_direction": "neutral reference key",
            },
            "shop_name": {
                "business_meaning": "Official shop name",
                "role": "text_attribute",
                "domain": "Retail",
                "unit": "text",
                "scale": "free_text",
                "data_type": "string",
                "value_direction": "neutral descriptive text",
            },
            "location": {
                "business_meaning": "City or locality where the shop is located",
                "role": "dimension",
                "domain": "Retail",
                "unit": "location",
                "scale": "nominal",
                "data_type": "string",
                "value_direction": "neutral geographic grouping",
            },
            "district": {
                "business_meaning": "Administrative district for the shop",
                "role": "dimension",
                "domain": "Retail",
                "unit": "district",
                "scale": "nominal",
                "data_type": "string",
                "value_direction": "neutral geographic grouping",
            },
            "postal_code": {
                "business_meaning": "Postal code assigned to the shop location",
                "role": "identifier",
                "domain": "Retail",
                "unit": "postal_code",
                "scale": "reference",
                "data_type": "string",
                "value_direction": "neutral location identifier",
            },
            "phone_number": {
                "business_meaning": "Shop contact phone number",
                "role": "identifier",
                "domain": "Retail",
                "unit": "phone",
                "scale": "reference",
                "data_type": "string",
                "value_direction": "neutral contact identifier",
            },
            "is_active": {
                "business_meaning": "Whether the shop is currently active in the retail network",
                "role": "binary_label",
                "domain": "Retail",
                "unit": "boolean",
                "scale": "binary",
                "data_type": "boolean",
                "value_direction": "true means active shop",
            },
            "operating_hours_open": {
                "business_meaning": "Daily opening time for the shop",
                "role": "timestamp",
                "domain": "Retail",
                "unit": "time",
                "scale": "time_of_day",
                "data_type": "string",
                "value_direction": "later means later opening time",
            },
            "operating_hours_close": {
                "business_meaning": "Daily closing time for the shop",
                "role": "timestamp",
                "domain": "Retail",
                "unit": "time",
                "scale": "time_of_day",
                "data_type": "string",
                "value_direction": "later means later closing time",
            },
        },
    },
    "trends": {
        "baseline_key": "trends",
        "dataset_name": "fashion_trends",
        "baseline_version": "v1",
        "description": "Approved semantic baseline for the trends table defined in data architecture.",
        "source_table": "trends_dataset.csv",
        "columns": {
            "trend_id": {
                "business_meaning": "Unique identifier for a tracked fashion trend",
                "role": "identifier",
                "domain": "Fashion Trends",
                "unit": "id",
                "scale": "integer",
                "data_type": "integer",
                "value_direction": "neutral reference key",
            },
            "trend_name": {
                "business_meaning": "Label of the trend being tracked",
                "role": "text_attribute",
                "domain": "Fashion Trends",
                "unit": "text",
                "scale": "free_text",
                "data_type": "string",
                "value_direction": "neutral descriptive text",
            },
            "trend_category": {
                "business_meaning": "Trend classification such as seasonal or category trend",
                "role": "dimension",
                "domain": "Fashion Trends",
                "unit": "category",
                "scale": "nominal",
                "data_type": "string",
                "value_direction": "neutral grouping",
            },
            "trend_score": {
                "business_meaning": "Trend strength or momentum score for the week",
                "role": "score",
                "domain": "Fashion Trends",
                "unit": "score",
                "scale": "normalized_score",
                "data_type": "decimal",
                "value_direction": "higher means stronger trend momentum",
            },
            "week": {
                "business_meaning": "Calendar week number used for trend tracking",
                "role": "dimension",
                "domain": "Fashion Trends",
                "unit": "week",
                "scale": "integer",
                "data_type": "integer",
                "value_direction": "higher means later week in the year",
            },
            "year": {
                "business_meaning": "Calendar year used for trend tracking",
                "role": "dimension",
                "domain": "Fashion Trends",
                "unit": "year",
                "scale": "integer",
                "data_type": "integer",
                "value_direction": "higher means more recent year",
            },
            "emerging_designers": {
                "business_meaning": "Designers associated with the observed trend",
                "role": "text_attribute",
                "domain": "Fashion Trends",
                "unit": "designer_names",
                "scale": "multi_label_text",
                "data_type": "string",
                "value_direction": "neutral descriptive association",
            },
            "trend_tags": {
                "business_meaning": "Tag bundle describing fabrics, aesthetics, and motifs linked to the trend",
                "role": "text_attribute",
                "domain": "Fashion Trends",
                "unit": "tags",
                "scale": "multi_label_text",
                "data_type": "string",
                "value_direction": "neutral descriptive tags",
            },
        },
    },
}


def get_predefined_baseline(baseline_key: str) -> Optional[Dict[str, Any]]:
    baseline = PREDEFINED_BASELINES.get(baseline_key)
    return deepcopy(baseline) if baseline else None


def list_predefined_baselines() -> List[Dict[str, Any]]:
    baselines: List[Dict[str, Any]] = []
    for baseline_key, baseline in PREDEFINED_BASELINES.items():
        baselines.append(
            {
                "baseline_key": baseline_key,
                "dataset_name": baseline["dataset_name"],
                "baseline_version": baseline["baseline_version"],
                "description": baseline.get("description", ""),
                "source_table": baseline.get("source_table", ""),
                "column_count": len(baseline.get("columns", {})),
                "columns": deepcopy(baseline.get("columns", {})),
            }
        )
    return baselines


def predefined_baseline_to_rows(template: Dict[str, Any]) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for column_name, column in template.get("columns", {}).items():
        rows.append(
            {
                "column_name": column_name,
                "business_meaning": column.get("business_meaning", ""),
                "role": column.get("role", "unknown"),
                "domain": column.get("domain", "General"),
                "unit": column.get("unit", "Unitless"),
                "scale": column.get("scale", "unknown"),
                "data_type": column.get("data_type", "unknown"),
                "value_direction": column.get("value_direction", "neutral"),
                "baseline_version": template.get("baseline_version", "v1"),
            }
        )
    return rows

